// マークダウン形式のレポート生成ユーティリティ

import { CATEGORY_CONFIG, getScoreLabel } from '@/data/default-personas';
import type { AnalysisResult, PersonaResult, PersonaCategory } from '@/types';

const SEVERITY_LABEL: Record<string, string> = {
  high: '高',
  medium: '中',
  low: '低',
};

/**
 * 分析結果をマークダウン形式のレポートに変換
 */
export function generateMarkdownReport(analysis: AnalysisResult): string {
  const scoreLabel = getScoreLabel(analysis.overallScore);
  const date = new Date(analysis.createdAt).toLocaleString('ja-JP');
  const lines: string[] = [];

  // ヘッダー
  lines.push('# SiteProbe 分析レポート');
  lines.push('');
  lines.push(`- **URL**: ${analysis.url}`);
  lines.push(`- **分析日**: ${date}`);
  lines.push(`- **総合スコア**: ${analysis.overallScore}/100（${scoreLabel.label}）`);
  lines.push('');

  // カテゴリ別スコア
  lines.push('## カテゴリ別スコア');
  lines.push('');
  lines.push('| カテゴリ | スコア |');
  lines.push('|----------|--------|');
  for (const cs of analysis.categoryScores) {
    lines.push(`| ${cs.label} | ${cs.score}点 |`);
  }
  lines.push('');

  // カテゴリ別にペルソナをグループ化
  const grouped = new Map<PersonaCategory, PersonaResult[]>();
  for (const p of analysis.personaResults) {
    if (p.status !== 'completed') continue;
    const list = grouped.get(p.personaCategory) ?? [];
    list.push(p);
    grouped.set(p.personaCategory, list);
  }

  // 各ペルソナの詳細
  lines.push('---');
  lines.push('');

  for (const [category, personas] of grouped) {
    const config = CATEGORY_CONFIG[category];
    const catScore = analysis.categoryScores.find((cs) => cs.category === category);
    lines.push(`## ${config?.label || category}（${catScore?.score ?? '-'}点）`);
    lines.push('');

    for (const persona of personas) {
      lines.push(`### ${persona.personaName} - ${persona.score}点`);
      lines.push('');
      lines.push(`> ${persona.summary}`);
      lines.push('');

      if (persona.findings.length > 0) {
        lines.push('#### 指摘事項');
        lines.push('');
        for (const finding of persona.findings) {
          const sev = SEVERITY_LABEL[finding.severity] || finding.severity;
          lines.push(`**[${sev}] ${finding.title}**`);
          lines.push('');
          lines.push(finding.description);
          lines.push('');
          if (finding.recommendation) {
            lines.push(`💡 **改善提案**: ${finding.recommendation}`);
            lines.push('');
          }
          if (finding.codeExample) {
            lines.push('```');
            lines.push(finding.codeExample);
            lines.push('```');
            lines.push('');
          }
        }
      }

      if (persona.thinkingProcess) {
        lines.push('<details>');
        lines.push('<summary>分析の思考過程</summary>');
        lines.push('');
        lines.push(persona.thinkingProcess);
        lines.push('');
        lines.push('</details>');
        lines.push('');
      }
    }
  }

  // フッター
  lines.push('---');
  lines.push('*Generated by SiteProbe - AI専門家チームによるサイト分析*');

  return lines.join('\n');
}

/**
 * テキストをファイルとしてダウンロード
 */
export function downloadTextFile(content: string, filename: string) {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
